# language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build -t jamespool/docker-react -f Dockerfile.dev .

# In the upcoming lecture we will be adding a script to our .travis.yml file. 
# Due to a change in how the Jest library works with Create React App, 
# we need to make a small modification:
# 
# script:
#   - docker run jamespool/docker-react npm run test -- --coverage
# 
# instead should be:
# 
script:
  - docker run -e CI=true jamespool/docker-react npm run test

deploy:
  # edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-142234334602"
  bucket_path: "docker-react"
  on:
    branch: master

# access_key_id: $AWS_ACCESS_KEY
# secret_access_key: $AWS_SECRET_KEY